-- colorscheme-treesitter.lua

local color = require "plain-colorscheme.colorscheme-color"

local M = {
    ["@attribute"]                  = { link = "Macro" },
    ["@attribute.builtin"]          = { link = "Special" },
    ["@boolean"]                    = { link = "Boolean" },
    ["@character"]                  = { link = "Character" },
    ["@character.special"]          = { link = "SpecialChar" },
    ["@comment"]                    = { link = "Comment" },
    ["@comment.error"]              = { link = "DiagnosticError" },
    ["@comment.note"]               = { link = "DiagnosticInfo" },
    ["@comment.todo"]               = { link = "Todo" },
    ["@comment.warning"]            = { link = "DiagnosticWarn" },
    ["@constant"]                   = { link = "Constant" },
    ["@constant.builtin"]           = { link = "Special" },
    ["@constructor"]                = { bg = color.none, fg = color.white },
    ["@diff.delta"]                 = { link = "Changed" },
    ["@diff.minus"]                 = { link = "Removed" },
    ["@diff.plus"]                  = { link = "Added" },
    ["@function"]                   = { link = "Function" },
    ["@function.builtin"]           = { link = "Special" },
    ["@keyword"]                    = { link = "Keyword" },
    ["@label"]                      = { link = "Label" },
    ["@markup"]                     = { bg = color.none, fg = color.gray_4 },
    ["@markup.heading"]             = { bg = color.none, fg = color.blue },
    ["@markup.italic"]              = { bg = color.none, fg = color.none },
    ["@markup.link"]                = { bg = color.none, fg = color.none },
    ["@markup.strikethrough"]       = { bg = color.none, fg = color.none },
    ["@markup.strong"]              = { bg = color.none, fg = color.none },
    ["@markup.underline"]           = { bg = color.none, fg = color.none },
    ["@module"]                     = { link = "Structure" },
    ["@module.builtin"]             = { link = "Special" },
    ["@number"]                     = { link = "Number" },
    ["@number.float"]               = { link = "Float" },
    ["@operator"]                   = { link = "Operator" },
    ["@property"]                   = { link = "Property" },
    ["@punctuation"]                = { link = "Delimiter" },
    ["@punctuation.special"]        = { link = "Special" },
    ["@spell.markdown"]             = { bg = color.none, fg = color.gray_2 },
    ["@string"]                     = { link = "String" },
    ["@string.escape"]              = { link = "@string.special" },
    ["@string.regexp"]              = { link = "@string.special" },
    ["@string.special"]             = { link = "SpecialChar" },
    ["@string.special.url"]         = { link = "Underlined" },
    ["@tag"]                        = { link = "Tag" },
    ["@tag.builtin"]                = { link = "Special" },
    ["@type"]                       = { link = "Type" },
    ["@type.builtin"]               = { link = "Special" },
    ["@variable"]                   = { link = "Identifier" },
    ["@variable.builtin"]           = { link = "Special" },
    ["@variable.parameter.builtin"] = { link = "Special" },
}

return M
