-- colorscheme-interface.lua

local color = require "plain-colorscheme.colorscheme-color"

local M = {
    Added                = { bg = color.none, fg = color.white },
    Changed              = { bg = color.none, fg = color.white },
    ColorColumn          = { bg = color.gray_0, fg = color.none },
    Conceal              = { bg = color.none, fg = color.white },
    CurSearch            = { bg = color.orange, fg = color.black },
    Cursor               = { bg = color.none, fg = color.white },
    CursorColumn         = { bg = color.none, fg = color.white },
    CursorIM             = { bg = color.none, fg = color.white },
    CursorLine           = { bg = color.gray_1, fg = color.none },
    CursorLineFold       = { link = "FoldColumn" },
    CursorLineNr         = { bg = color.none, fg = color.white },
    CursorLineSign       = { link = "SignColumn" },
    DiffAdd              = { bg = color.none, fg = color.green },
    DiffChange           = { bg = color.none, fg = color.green },
    DiffDelete           = { bg = color.none, fg = color.red },
    DiffText             = { bg = color.none, fg = color.red },
    Directory            = { bg = color.none, fg = color.green },
    EndOfBuffer          = { bg = color.none, fg = color.gray_1 },
    ErrorMsg             = { bg = color.none, fg = color.red },
    FloatBorder          = { bg = color.none, fg = color.gray_1 },
    FloatFooter          = { bg = color.none, fg = color.white },
    FloatShadow          = { bg = color.none, fg = color.white },
    FloatShadowThrough   = { bg = color.none, fg = color.white },
    FloatTitle           = { bg = color.none, fg = color.white },
    FoldColumn           = { bg = color.none, fg = color.gray_3 },
    Folded               = { bg = color.none, fg = color.gray_3 },
    IncSearch            = { bg = color.orange, fg = color.black },
    LineNr               = { bg = color.none, fg = color.white },
    LineNrAbove          = { bg = color.none, fg = color.gray_2 },
    LineNrBelow          = { bg = color.none, fg = color.gray_2 },
    MatchParen           = { bg = color.gray_1, fg = color.none },
    ModeMsg              = { bg = color.none, fg = color.white },
    MoreMsg              = { bg = color.none, fg = color.white },
    MsgArea              = { bg = color.none, fg = color.white },
    MsgSeparator         = { bg = color.none, fg = color.white },
    NonText              = { bg = color.none, fg = color.gray_1 },
    Normal               = { bg = color.none, fg = color.white },
    NormalFloat          = { bg = color.none, fg = color.white },
    NormalNC             = { bg = color.none, fg = color.white },
    Pmenu                = { bg = color.none, fg = color.gray_3 },
    PmenuExtra           = { bg = color.none, fg = color.gray_2 },
    PmenuExtraSel        = { bg = color.gray_0, fg = color.gray_3 },
    PmenuKind            = { bg = color.none, fg = color.blue },
    PmenuKindSel         = { bg = color.gray_0, fg = color.blue },
    PmenuMatch           = { bg = color.none, fg = color.white },
    PmenuMatchSel        = { bg = color.none, fg = color.white },
    PmenuSbar            = { bg = color.gray_0, fg = color.white },
    PmenuSel             = { bg = color.gray_0, fg = color.white },
    PmenuThumb           = { bg = color.gray_1, fg = color.white },
    Question             = { bg = color.none, fg = color.white },
    QuickFixLine         = { bg = color.none, fg = color.blue },
    RedrawDebugClear     = { bg = color.none, fg = color.white },
    RedrawDebugComposed  = { bg = color.none, fg = color.white },
    RedrawDebugNormal    = { bg = color.none, fg = color.white },
    RedrawDebugRecompose = { bg = color.none, fg = color.white },
    Removed              = { bg = color.none, fg = color.white },
    Search               = { bg = color.yellow, fg = color.black },
    SignColumn           = { bg = color.gray_0, fg = color.white },
    SpecialKey           = { bg = color.none, fg = color.gray_2 },
    SpellBad             = { bg = color.none, fg = color.white },
    SpellCap             = { bg = color.none, fg = color.white },
    SpellLocal           = { bg = color.none, fg = color.white },
    SpellRare            = { bg = color.none, fg = color.white },
    StatusLine           = { bg = color.gray_0, fg = color.gray_3 },
    StatusLineNC         = { bg = color.gray_0, fg = color.gray_2 },
    StatusLineTerm       = { bg = color.none, fg = color.white },
    StatusLineTermNC     = { bg = color.none, fg = color.white },
    Substitute           = { bg = color.yellow, fg = color.black },
    TabLine              = { bg = color.none, fg = color.white },
    TabLineFill          = { bg = color.none, fg = color.white },
    TabLineSel           = { bg = color.none, fg = color.white },
    TermCursor           = { reverse = true },
    TermCursorNC         = { bg = color.none, fg = color.none },
    Title                = { bg = color.none, fg = color.blue },
    VertSplit            = { link = "WinSeparator" },
    Visual               = { bg = color.gray_1, fg = color.none },
    VisualNOS            = { bg = color.none, fg = color.white },
    WarningMsg           = { bg = color.none, fg = color.white },
    Whitespace           = { link = "NonText" },
    WildMenu             = { bg = color.none, fg = color.white },
    WinBar               = { bg = color.none, fg = color.white },
    WinBarNC             = { bg = color.none, fg = color.white },
    WinSeparator         = { bg = color.none, fg = color.gray_1 },
    lCursor              = { bg = color.none, fg = color.white },
}

return M
